=== ThePotatoArchivist/RPGSkills/assets/schemas/class.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Identifier": {
      "pattern": "^[a-z0-9_.-]+:[a-z0-9/._-]+$",
      "type": "string"
    },
    "ItemStack": {
      "additionalProperties": false,
      "properties": {
        "components": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^[a-z0-9_.-]+:[a-z0-9/._-]+$": {}
          }
        },
        "count": {
          "type": "integer",
          "minimum": 1
        },
        "id": {
          "$ref": "#/definitions/Identifier"
        }
      },
      "required": [
        "id"
      ],
      "type": "object"
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string"
    },
    "icon": {
      "anyOf": [
        {
          "$ref": "#/definitions/ItemStack"
        },
        {
          "$ref": "#/definitions/Identifier"
        }
      ]
    },
    "description": {
      "type": "string"
    },
    "starting_levels": {
      "type": "object",
      "patternProperties": {
        "^[a-z0-9_.-]+:[a-z0-9/._-]+$": {
          "type": "integer",
          "minimum": 1
        }
      }
    }
  },
  "required": [
    "name",
    "icon",
    "description",
    "starting_levels"
  ]
}

=== ThePotatoArchivist/RPGSkills/src/main/generated/resourcepacks/test_pack/data/rpg_test/rpgskills/class/engineer.json
{
  "description": "Hello and welcome to my TED talk. This is a very long description text to make sure that wrapping and scrolling works properly. I hope you had a good time reading it.",
  "icon": {
    "id": "minecraft:comparator"
  },
  "name": "Engineer",
  "starting_levels": {
    "rpg_test:cow": 2,
    "rpg_test:potato": 1
  }
}
