=== ThePotatoArchivist/RPGSkills/assets/schemas/job.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Identifier": {
      "pattern": "^[a-z0-9_.-]+:[a-z0-9/._-]+$",
      "type": "string"
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "cooldown_ticks": {
      "type": "integer",
      "minimum": 0
    },
    "reward_points": {
      "type": "integer",
      "minimum": 0
    },
    "spawn_as_orbs": {
      "type": "boolean"
    },
    "tasks": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "pattern": "[a-z0-9_]+"
          },
          "trigger": {
            "$ref": "#/definitions/Identifier",
            "description": "See https://misode.github.io/advancement/"
          },
          "conditions": {
            "type": "object",
            "description": "See https://misode.github.io/advancement/"
          },
          "description": {
            "type": "string"
          },
          "count": {
            "type": "integer",
            "minimum": 1
          }
        },
        "additionalProperties": false,
        "required": [
          "trigger",
          "id",
          "description",
          "count"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "name",
    "cooldown_ticks",
    "reward_points",
    "tasks"
  ]
}

=== ThePotatoArchivist/RPGSkills/src/main/generated/resourcepacks/test_pack/data/rpg_test/rpgskills/job/stand_on_iron.json
{
  "cooldown_ticks": 600,
  "name": "Stand on iron",
  "reward_points": 200,
  "tasks": [
    {
      "conditions": {
        "player": [
          {
            "condition": "minecraft:entity_properties",
            "entity": "this",
            "predicate": {
              "stepping_on": {
                "block": {
                  "blocks": "minecraft:iron_block"
                }
              }
            }
          }
        ]
      },
      "count": 600,
      "description": "Stand on iron",
      "id": "stand",
      "trigger": "minecraft:tick"
    }
  ]
}

=== ThePotatoArchivist/RPGSkills/src/main/generated/resourcepacks/test_pack/data/rpg_test/rpgskills/job/breed.json
{
  "cooldown_ticks": 2000,
  "name": "Breed",
  "reward_points": 20,
  "tasks": [
    {
      "conditions": {
        "parent": [
          {
            "condition": "minecraft:entity_properties",
            "entity": "this",
            "predicate": {
              "type": [
                "minecraft:cow",
                "minecraft:pig",
                "minecraft:sheep",
                "minecraft:chicken"
              ]
            }
          }
        ]
      },
      "count": 4,
      "description": "Breed animals",
      "id": "breed",
      "trigger": "minecraft:bred_animals"
    }
  ]
}
