=== ThePotatoArchivist/RPGSkills/assets/schemas/lock_group.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Identifier": {
      "type": "string",
      "pattern": "^[a-z0-9_.-]+:[a-z0-9/._-]+$"
    },
    "Tag": {
      "type": "string",
      "pattern": "^#[a-z0-9_.-]+:[a-z0-9/._-]+$"
    },
    "RegistryEntryList": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "#/definitions/Identifier"
          },
          {
            "$ref": "#/definitions/Tag"
          }
        ]
      }
    },
    "LockList": {
      "anyOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "message": {
              "type": "string"
            },
            "entries": {
              "$ref": "#/definitions/RegistryEntryList"
            }
          },
          "required": [
            "entries"
          ]
        },
        {
          "$ref": "#/definitions/RegistryEntryList"
        }
      ]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "blocks": {
      "$ref": "#/definitions/LockList"
    },
    "entities": {
      "$ref": "#/definitions/LockList"
    },
    "items": {
      "$ref": "#/definitions/LockList"
    },
    "enchantments": {
      "$ref": "#/definitions/LockList"
    },
    "recipes": {
      "$ref": "#/definitions/LockList"
    },
    "item_components": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[a-z0-9_.-]+:[a-z0-9/._-]+$": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "type": {
              "$ref": "#/definitions/Identifier"
            },
            "values": {
              "type": "array",
              "minItems": 1
            }
          },
          "required": [
            "type",
            "values"
          ]
        }
      }
    },
    "requirements": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "patternProperties": {
          "^[a-z0-9_.-]+:[a-z0-9/._-]+$": {
            "type": "integer"
          }
        }
      }
    }
  },
  "required": [
    "requirements"
  ]
}

=== ThePotatoArchivist/RPGSkills/src/main/generated/resourcepacks/test_pack/data/rpg_test/rpgskills/lockgroup/potato1.json
{
  "blocks": [
    "minecraft:crafting_table",
    "minecraft:end_gateway"
  ],
  "items": {
    "entries": [
      "minecraft:potato",
      "minecraft:poisonous_potato",
      "minecraft:ender_eye"
    ],
    "message": "You don't know if this potato is safe to eat"
  },
  "recipes": {
    "entries": [
      "minecraft:baked_potato"
    ],
    "message": "You don't know how to cook this potato"
  },
  "requirements": [
    {
      "rpg_test:potato": 1
    }
  ]
}

=== ThePotatoArchivist/RPGSkills/src/main/generated/resourcepacks/test_pack/data/rpg_test/rpgskills/lockgroup/potato3.json
{
  "blocks": {
    "entries": [
      "#minecraft:buttons"
    ],
    "message": "How to press?"
  },
  "item_components": {
    "minecraft:goat_horn": {
      "type": "minecraft:instrument",
      "values": [
        "minecraft:admire_goat_horn"
      ]
    },
    "minecraft:potion": {
      "type": "minecraft:potion_contents",
      "tooltip_index": 1,
      "values": [
        {
          "potion": "minecraft:turtle_master"
        }
      ]
    }
  },
  "items": {
    "entries": [
      "minecraft:red_concrete",
      "minecraft:blue_concrete",
      "#minecraft:buttons"
    ],
    "message": "You don't know what kind of button this is"
  },
  "recipes": {
    "entries": [
      "#minecraft:buttons"
    ],
    "message": "You don't know how to assemble this button"
  },
  "requirements": [
    {
      "rpg_test:cow": 1,
      "rpg_test:potato": 3
    },
    {
      "rpg_test:cow": 1,
      "rpg_test:grass": 2
    }
  ]
}

=== ThePotatoArchivist/RPGSkills/src/main/generated/resourcepacks/test_pack/data/rpg_test/rpgskills/lockgroup/potato2.json
{
  "enchantments": [
    "minecraft:aqua_affinity"
  ],
  "entities": {
    "entries": [
      "minecraft:villager",
      "minecraft:chicken",
      "minecraft:armor_stand",
      "minecraft:tnt_minecart",
      "minecraft:boat"
    ],
    "message": "AAA"
  },
  "items": {
    "entries": [
      "minecraft:trident",
      "minecraft:diamond_helmet",
      "minecraft:cod",
      "minecraft:chest_minecart",
      "minecraft:armor_stand",
      "minecraft:arrow",
      "#minecraft:boats"
    ],
    "message": "You don't know how to eat with this fork"
  },
  "recipes": {
    "entries": [
      "minecraft:prismarine_bricks",
      "minecraft:netherite_helmet"
    ],
    "message": "You don't know how to assemble this prismarine"
  },
  "requirements": [
    {
      "rpg_test:potato": 2
    },
    {
      "rpg_test:cow": 2
    },
    {
      "rpg_test:grass": 2
    }
  ]
}
