=== ThePotatoArchivist/RPGSkills/assets/schemas/build/skill.json
{
  "$ref": "#/definitions/Skill",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Identifier": {
      "pattern": "^[a-z0-9_.-]+:[a-z0-9/._-]+$",
      "type": "string"
    },
    "ItemStack": {
      "additionalProperties": false,
      "properties": {
        "components": {
          "additionalProperties": {},
          "type": "object"
        },
        "count": {
          "$ref": "#/definitions/integer"
        },
        "id": {
          "$ref": "#/definitions/Identifier"
        }
      },
      "required": [
        "id"
      ],
      "type": "object"
    },
    "Level": {
      "additionalProperties": false,
      "properties": {
        "attributes": {
          "additionalProperties": false,
          "patternProperties": {
            "^[a-z0-9_.-]+:[a-z0-9/._-]+$": {
              "additionalProperties": false,
              "properties": {
                "amount": {
                  "type": "number"
                },
                "operation": {
                  "enum": [
                    "add_value",
                    "add_multiplied_base",
                    "add_multiplied_total"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "amount",
                "operation"
              ],
              "type": "object"
            }
          },
          "type": "object"
        },
        "cost": {
          "$ref": "#/definitions/integer"
        }
      },
      "required": [
        "cost",
        "attributes"
      ],
      "type": "object"
    },
    "Skill": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        },
        "icon": {
          "$ref": "#/definitions/ItemStack"
        },
        "levels": {
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/Level"
              },
              {
                "$ref": "#/definitions/integer"
              }
            ]
          },
          "type": "array"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "icon",
        "levels"
      ],
      "type": "object"
    },
    "integer": {
      "type": "integer"
    }
  }
}

=== ThePotatoArchivist/RPGSkills/src/main/generated/resourcepacks/test_pack/data/rpg_test/rpgskills/skills/potato.json
{
  "description": "Unlocks potatoes & other stuff",
  "icon": {
    "count": 1,
    "id": "minecraft:potato"
  },
  "levels": [
    {
      "attributes": {
        "minecraft:generic.movement_speed": {
          "amount": 0.1,
          "operation": "add_multiplied_base"
        }
      },
      "cost": 1
    },
    {
      "attributes": {
        "minecraft:generic.movement_speed": {
          "amount": 0.1,
          "operation": "add_multiplied_base"
        }
      },
      "cost": 2
    },
    3
  ],
  "name": "Potato Skill"
}

=== ThePotatoArchivist/RPGSkills/src/main/generated/resourcepacks/default_pack/data/rpg_test/rpgskills/skills/potato.json
{
  "description": "Unlocks potatoes & other stuff",
  "icon": {
    "count": 1,
    "id": "minecraft:potato"
  },
  "levels": [
    {
      "attributes": {
        "minecraft:generic.movement_speed": 2.0
      },
      "cost": 1
    },
    {
      "attributes": {
        "minecraft:generic.movement_speed": 0.5
      },
      "cost": 2
    },
    3
  ],
  "name": "Potato Skill"
}

=== ThePotatoArchivist/RPGSkills/src/main/generated/resourcepacks/test_pack/data/rpg_test/rpgskills/skill/potato.json
{
  "description": "Unlocks potatoes & other stuff",
  "icon": {
    "id": "minecraft:potato"
  },
  "levels": [
    {
      "attributes": {
        "minecraft:generic.movement_speed": {
          "amount": 0.1,
          "operation": "add_multiplied_base"
        }
      },
      "cost": 1
    },
    {
      "attributes": {
        "minecraft:generic.movement_speed": {
          "amount": 0.1,
          "operation": "add_multiplied_base"
        }
      },
      "cost": 2
    },
    3
  ],
  "name": "Potato Skill"
}
